name: build

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'staging'
      - '!v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build concepts
    runs-on: ubuntu-latest
    steps:
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl
      - name: Setup snaps
        run: |
          sudo snap install yq
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - uses: actions/checkout@master
      - name: Setup git submodules (authenticated)
        env:
          MLGT_DATA_DEPLOY_KEY: ${{ secrets.GEOLEXICA_DATABASE_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MLGT_DATA_DEPLOY_KEY}"
          make update-init update-modules
      - name: Install gems
        run: |
          gem install bundler -v "~> 2"
          bundle install --jobs 4 --retry 3
      - name: Build concept files
        run: |
          make distclean all tc211-termbase.zip
